yii2-app-basic/models/Builds.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "builds".
 *
 * @property string $nombre
 * @property string|null $descripcion
 * @property string|null $fcreacion
 * @property int|null $efectividad
 * @property int|null $complejidad
 * @property int|null $idpersonaje
 * @property int|null $idcascos
 * @property int|null $idcollar
 * @property int|null $idarma
 * @property int|null $idarmadura
 * @property int|null $idbotas
 * @property int|null $idanillo
 * @property int|null $idvelbotas
 *
 * @property Anillos $idanillo0
 * @property Armas $idarma0
 * @property Armaduras $idarmadura0
 * @property Botas $idbotas0
 * @property Velocidadbotas $idbotas1
 * @property Cascos $idcascos0
 * @property Collares $idcollar0
 * @property Personajes $idpersonaje0
 * @property int $idbuild
 * @property string $nombre
 * @property int $idpersonaje
 * @property int $idarmadura
 * @property int $idanillo
 * @property int $idcascos
 * @property int $idbotas
 * @property int $idarma
 *
 * @property Personajes $personaje
 * @property Armadura $armadura
 * @property Anillo $anillo
 * @property Cascos $cascos
 * @property Botas $botas
 * @property Arma $arma
 */
class Builds extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'builds';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['fcreacion'], 'safe'],
            [['efectividad', 'complejidad', 'idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas', 'idanillo', 'idvelbotas'], 'integer'],
            [['nombre'], 'string', 'max' => 50],
            [['descripcion'], 'string', 'max' => 500],
            [['idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas'], 'unique', 'targetAttribute' => ['idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas']],
            [['nombre'], 'unique'],
            [['idanillo'], 'exist', 'skipOnError' => true, 'targetClass' => Anillos::class, 'targetAttribute' => ['idanillo' => 'idanillo']],
            [['idarmadura'], 'exist', 'skipOnError' => true, 'targetClass' => Armaduras::class, 'targetAttribute' => ['idarmadura' => 'idarmadura']],
            [['idarma'], 'exist', 'skipOnError' => true, 'targetClass' => Armas::class, 'targetAttribute' => ['idarma' => 'idarma']],
            [['idbotas'], 'exist', 'skipOnError' => true, 'targetClass' => Botas::class, 'targetAttribute' => ['idbotas' => 'idbotas']],
            [['idcascos'], 'exist', 'skipOnError' => true, 'targetClass' => Cascos::class, 'targetAttribute' => ['idcascos' => 'idcasco']],
            [['idcollar'], 'exist', 'skipOnError' => true, 'targetClass' => Collares::class, 'targetAttribute' => ['idcollar' => 'idcollar']],
            [['idpersonaje'], 'exist', 'skipOnError' => true, 'targetClass' => Personajes::class, 'targetAttribute' => ['idpersonaje' => 'idpersonaje']],
            [['idbotas'], 'exist', 'skipOnError' => true, 'targetClass' => Velocidadbotas::class, 'targetAttribute' => ['idbotas' => 'idbotas']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'fcreacion' => 'Fcreacion',
            'efectividad' => 'Efectividad',
            'complejidad' => 'Complejidad',
            'idpersonaje' => 'Idpersonaje',
            'idcascos' => 'Idcascos',
            'idcollar' => 'Idcollar',
            'idarma' => 'Idarma',
            'idarmadura' => 'Idarmadura',
            'idbotas' => 'Idbotas',
            'idanillo' => 'Idanillo',
            'idvelbotas' => 'Idvelbotas',
        ];
    }

    /**
     * Gets query for [[Idanillo0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdanillo0()
    {
        return $this->hasOne(Anillos::class, ['idanillo' => 'idanillo']);
    }

    /**
     * Gets query for [[Idarma0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdarma0()
    {
        return $this->hasOne(Armas::class, ['idarma' => 'idarma']);
    }

    /**
     * Gets query for [[Idarmadura0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdarmadura0()
    {
        return $this->hasOne(Armaduras::class, ['idarmadura' => 'idarmadura']);
    }

    /**
     * Gets query for [[Idbotas0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdbotas0()
    {
        return $this->hasOne(Botas::class, ['idbotas' => 'idbotas']);
    }

    /**
     * Gets query for [[Idbotas1]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdbotas1()
    {
        return $this->hasOne(Velocidadbotas::class, ['idbotas' => 'idbotas']);
    }

    /**
     * Gets query for [[Idcascos0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdcascos0()
    {
        return $this->hasOne(Cascos::class, ['idcasco' => 'idcascos']);
    }

    /**
     * Gets query for [[Idcollar0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdcollar0()
    {
        return $this->hasOne(Collares::class, ['idcollar' => 'idcollar']);
    }

    /**
     * Gets query for [[Idpersonaje0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdpersonaje0()
    {
        return $this->hasOne(Personajes::class, ['idpersonaje' => 'idpersonaje']);
    }
}

yii2-app-basic/controllers/BuildsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Builds;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * BuildsController implements the CRUD actions for Builds model.
 */
class BuildsController extends Controller
{
    public static function tableName()
    {
        return 'builds';
    }

    // Define las reglas de validación
    public function rules()
    {
        return [
            [['nombre', 'idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas', 'idanillo', 'idvelbotas'], 'required'],
            [['descripcion'], 'string'],
            [['fcreacion'], 'safe'],
            [['efectividad', 'complejidad', 'idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas', 'idanillo', 'idvelbotas'], 'integer'],
            [['nombre'], 'string', 'max' => 50],
            [['nombre'], 'unique'],
            [['idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas'], 'unique', 'targetAttribute' => ['idpersonaje', 'idcascos', 'idcollar', 'idarma', 'idarmadura', 'idbotas']],
        ];
    }

    // Define etiquetas para los atributos
    public function attributeLabels()
    {
        return [
            'nombre' => 'Nombre',
            'descripcion' => 'Descripción',
            'fcreacion' => 'Fecha de Creación',
            'efectividad' => 'Efectividad',
            'complejidad' => 'Complejidad',
            'idpersonaje' => 'Personaje',
            'idcascos' => 'Casco',
            'idcollar' => 'Collar',
            'idarma' => 'Arma',
            'idarmadura' => 'Armadura',
            'idbotas' => 'Botas',
            'idanillo' => 'Anillo',
            'idvelbotas' => 'Velocidad de Botas',
        ];
    }

    // Define las relaciones
    public function getPersonaje()
    {
        return $this->hasOne(Personajes::class, ['idpersonaje' => 'idpersonaje']);
    }

    public function getCasco()
    {
        return $this->hasOne(Cascos::class, ['idcasco' => 'idcascos']);
    }

    public function getCollar()
    {
        return $this->hasOne(Collares::class, ['idcollar' => 'idcollar']);
    }

    public function getArma()
    {
        return $this->hasOne(Armas::class, ['idarma' => 'idarma']);
    }

    public function getArmadura()
    {
        return $this->hasOne(Armaduras::class, ['idarmadura' => 'idarmadura']);
    }

    public function getBotas()
    {
        return $this->hasOne(Botas::class, ['idbotas' => 'idbotas']);
    }

    public function getAnillo()
    {
        return $this->hasOne(Anillos::class, ['idanillo' => 'idanillo']);
    }

    public function getVelbotas()
    {
        return $this->hasOne(Velocidadbotas::class, ['idbotas' => 'idvelbotas']);
    }
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }
    public function actionCompare()
    {
        $build1 = null;
        $build2 = null;
        $statistics = [];

        if (Yii::$app->request->post()) {
            $id1 = Yii::$app->request->post('build1');
            $id2 = Yii::$app->request->post('build2');

            if ($id1 && $id2) {
                $build1 = Builds::findOne(['nombre' => $id1]);
                $build2 = Builds::findOne(['nombre' => $id2]);

                if (!$build1 || !$build2) {
                    throw new NotFoundHttpException('Una o ambas builds no fueron encontradas.');
                }

                // Estadísticas específicas para la comparación
                $statistics = [
                    'Armadura' => [
                        'valordef' => [$build1->idarmadura0->valordef ?? 'N/A', $build2->idarmadura0->valordef ?? 'N/A'],
                        'porcentfisicodef' => [$build1->idarmadura0->porcentfisicodef ?? 'N/A', $build2->idarmadura0->porcentfisicodef ?? 'N/A'],
                        'porcentelementaldef' => [$build1->idarmadura0->porcentelementaldef ?? 'N/A', $build2->idarmadura0->porcentelementaldef ?? 'N/A'],
                    ],
                    'Anillo' => [
                        'probcrit' => [$build1->idanillo0->probcrit ?? 'N/A', $build2->idanillo0->probcrit ?? 'N/A'],
                    ],
                    'Cascos' => [
                        'vidaextra' => [$build1->idcascos0->vidaextra ?? 'N/A', $build2->idcascos0->vidaextra ?? 'N/A'],
                        'regen' => [$build1->idcascos0->regen ?? 'N/A', $build2->idcascos0->regen ?? 'N/A'],
                    ],
                    'Botas' => [
                        'porcentevasion' => [$build1->idbotas0->porcentevasion ?? 'N/A', $build2->idbotas0->porcentevasion ?? 'N/A'],
                    ],
                    'Arma' => [
                        'valoratk' => [$build1->idarma0->valoratk ?? 'N/A', $build2->idarma0->valoratk ?? 'N/A'],
                        'porcentfisicoatk' => [$build1->idarma0->porcentfisicoatk ?? 'N/A', $build2->idarma0->porcentfisicoatk ?? 'N/A'],
                        'porcentelementalatk' => [$build1->idarma0->porcentelementalatk ?? 'N/A', $build2->idarma0->porcentelementalatk ?? 'N/A'],
                    ],
                    'Velocidad Botas' => [
                        'velmovimiento' => [$build1->idbotas1->velmovimiento ?? 'N/A', $build2->idbotas1->velmovimiento ?? 'N/A'],
                    ],
                ];
            }
        }

        return $this->render('compare', [
            'build1' => $build1,
            'build2' => $build2,
            'statistics' => $statistics,
        ]);
    }




    /**
     * Lists all Builds models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Builds::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionBuscar()
    {
        // Consulta SQL para obtener los datos requeridos
        $sqlTodasBuilds = '
        SELECT 
            b.nombre AS nombre,
            b.complejidad AS complejidad,
            b.efectividad AS efectividad,
            p.nombreesp AS personaje_nombre
        FROM 
            builds b
        LEFT JOIN 
            personajes p ON b.idpersonaje = p.idpersonaje
        ';

        // Configuración para el SqlDataProvider de 'todasBuilds'
        $dataProviderTodasBuilds = new SqlDataProvider([
            'sql' => $sqlTodasBuilds,
        ]);

        // Consulta SQL para obtener las tres builds más recientes
        $sqlTresRecientes = '
        SELECT 
            b.nombre AS nombre,
            b.fcreacion AS fecha_creacion,
            b.efectividad AS efectividad,
            b.complejidad AS complejidad,
            p.nombreesp AS personaje_nombre
        FROM 
            builds b
        LEFT JOIN 
            personajes p ON b.idpersonaje = p.idpersonaje
        ORDER BY 
            b.fcreacion DESC
        LIMIT 3
        ';

        // Configuración para el SqlDataProvider de 'tresRecientes'
        $dataProviderTresRecientes = new SqlDataProvider([
            'sql' => $sqlTresRecientes,
            'pagination' => false, // Desactiva la paginación
            'sort' => false,       // Desactiva el ordenamiento
        ]);

        // Renderiza la vista 'buscar' con los datos proporcionados
        return $this->render('buscar', [
            'todasBuilds' => $dataProviderTodasBuilds,
            'tresRecientes' => $dataProviderTresRecientes,
        ]);
    }
    public function actionVer($nombre)
    {
        // Consulta SQL para obtener los datos de la build específica
        $sqlBuild = '
        SELECT 
            b.nombre AS nombre,
            b.descripcion AS descripcion,
            b.fcreacion AS fecha_creacion,
            b.efectividad AS efectividad,
            b.complejidad AS complejidad,
            p.nombreesp AS personaje_nombre,
            c.nombre AS casco_nombre,
            c.vidaextra AS casco_vidaextra,
            c.regen AS casco_regen,
            col.nombre AS collar_nombre,
            col.efectoesp AS collar_efectoesp,
            a.nombre AS arma_nombre,
            a.valoratk AS arma_valoratk,
            a.porcentfisicoatk AS arma_porcentfisicoatk,
            a.porcentelementalatk AS arma_porcentelementalatk,
            arm.nombre AS armadura_nombre,
            arm.valordef AS armadura_valordef,
            arm.porcentfisicodef AS armadura_porcentfisicodef,
            arm.porcentelementaldef AS armadura_porcentelementaldef,
            bot.nombre AS botas_nombre,
            bot.porcentevasion AS botas_porcentevasion,
            an.nombre AS anillo_nombre,
            an.probcrit AS anillo_probcrit,
            vb.velmovimiento AS velocidad_botas
        FROM 
            builds b
        LEFT JOIN 
            personajes p ON b.idpersonaje = p.idpersonaje
        LEFT JOIN 
            cascos c ON b.idcascos = c.idcasco
        LEFT JOIN 
            collares col ON b.idcollar = col.idcollar
        LEFT JOIN 
            armas a ON b.idarma = a.idarma
        LEFT JOIN 
            armaduras arm ON b.idarmadura = arm.idarmadura
        LEFT JOIN 
            botas bot ON b.idbotas = bot.idbotas
        LEFT JOIN 
            anillos an ON b.idanillo = an.idanillo
        LEFT JOIN 
            velocidadbotas vb ON b.idvelbotas = vb.idbotas
        WHERE 
            b.nombre = :nombre
        ';

        // Ejecutar la consulta
        $build = Yii::$app->db->createCommand($sqlBuild, [':nombre' => $nombre])->queryOne();

yii2-app-basic/views/builds/altaefec.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var yii\data\SqlDataProvider $altaEfectivas */
/** @var array $campos2 */

$this->title = 'Builds con Efectividad Alta';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="contenedor-titulo">
    <h1 class="titulo">BUILDS CON EFECTIVIDAD ALTA</h1>
</div>

<div class="contenedor-tabla-tresrecientes">
    <?= GridView::widget([
        'dataProvider' => $altaEfectivas,
        'columns' => [
            [
                'attribute' => 'nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model['nombre']), ['builds/ver', 'nombre' => $model['nombre']]);
                },
            ],
            [
                'attribute' => 'efectividad',
                'value' => function ($model) {
                    return $model['efectividad'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'complejidad',
                'value' => function ($model) {
                    return $model['complejidad'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'personaje_nombre',
                'label' => 'Personaje',
                'value' => function ($model) {
                    return $model['personaje_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'casco_nombre',
                'label' => 'Casco',
                'value' => function ($model) {
                    return $model['casco_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'collar_nombre',
                'label' => 'Collar',
                'value' => function ($model) {
                    return $model['collar_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'arma_nombre',
                'label' => 'Arma',
                'value' => function ($model) {
                    return $model['arma_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'armadura_nombre',
                'label' => 'Armadura',
                'value' => function ($model) {
                    return $model['armadura_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'botas_nombre',
                'label' => 'Botas',
                'value' => function ($model) {
                    return $model['botas_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'anillo_nombre',
                'label' => 'Anillo',
                'value' => function ($model) {
                    return $model['anillo_nombre'] ?: 'N/A';
                }
            ],
        ],
        'summary' => '', // Oculta el resumen de la cantidad de elementos
        'emptyText' => 'No se encontraron registros con efectividad alta.',
        'options' => [
            'class' => 'tabla-tresRecientes', // Aplica la clase CSS personalizada al GridView
        ],
    ]); ?>
</div>

<div class="contenedor-titulo">
    <?= Html::a('VOLVER A EXPLORAR', ['builds/explorar'], ['class' => 'boton-vuelta-a-explorar']) ?>
</div>

yii2-app-basic/views/builds/bajaefec.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var yii\data\SqlDataProvider $pocoEfectivas */
/** @var array $campos2 */

$this->title = 'Builds con Efectividad Baja';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="contenedor-titulo">
    <h1 class="titulo">BUILDS CON EFECTIVIDAD BAJA</h1>
</div>

<div class="contenedor-tabla-tresrecientes">
    <?= GridView::widget([
        'dataProvider' => $pocoEfectivas,
        'columns' => [
            [
                'attribute' => 'nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model['nombre']), ['builds/ver', 'nombre' => $model['nombre']]);
                },
            ],
            [
                'attribute' => 'efectividad',
                'value' => function ($model) {
                    return $model['efectividad'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'complejidad',
                'value' => function ($model) {
                    return $model['complejidad'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'personaje_nombre',
                'label' => 'Personaje',
                'value' => function ($model) {
                    return $model['personaje_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'casco_nombre',
                'label' => 'Casco',
                'value' => function ($model) {
                    return $model['casco_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'collar_nombre',
                'label' => 'Collar',
                'value' => function ($model) {
                    return $model['collar_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'arma_nombre',
                'label' => 'Arma',
                'value' => function ($model) {
                    return $model['arma_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'armadura_nombre',
                'label' => 'Armadura',
                'value' => function ($model) {
                    return $model['armadura_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'botas_nombre',
                'label' => 'Botas',
                'value' => function ($model) {
                    return $model['botas_nombre'] ?: 'N/A';
                }
            ],
            [
                'attribute' => 'anillo_nombre',
                'label' => 'Anillo',
                'value' => function ($model) {
                    return $model['anillo_nombre'] ?: 'N/A';
                }
            ],
        ],
        'summary' => '', // Oculta el resumen de la cantidad de elementos
        'emptyText' => 'No se encontraron registros con efectividad baja.',
        'options' => [
            'class' => 'tabla-tresRecientes', // Aplica la clase CSS personalizada al GridView
        ],
    ]); ?>
</div>

<div class="contenedor-titulo">
    <?= Html::a('VOLVER A EXPLORAR', ['builds/explorar'], ['class' => 'boton-vuelta-a-explorar']) ?>
</div>

yii2-app-basic/views/builds/dificil.php
<?php

use app\models\Builds;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\web\Controller;
use yii\data\SqlDataProvider;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Builds';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="contenedor-titulo">
    <h1 class="titulo">BUILDS DE DIFICULTAD ALTA</h1>
</div>

<div class="contenedor-tabla-tresrecientes">
    <?= GridView::widget([
        'dataProvider' => $faciles,
        'columns' => [
            [
                'attribute' => 'nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model['nombre']), ['builds/ver', 'nombre' => $model['nombre']]);
                },
            ],
            'efectividad',
            'complejidad',
            'personaje_nombre',
            'casco_nombre',
            'collar_nombre',
            'arma_nombre',
            'armadura_nombre',
            'botas_nombre',
            'anillo_nombre',
        ],
        'tableOptions' => ['class' => 'tabla-tresRecientes'],
        'summary' => '', // Oculta el resumen
    ]); ?>
</div>

<!--boton de vuelta-->
<div class="contenedor-titulo">
    <?= Html::a('VOLVER A EXPLORAR', ['builds/explorar'], ['class' => 'boton-vuelta-a-explorar']) ?>
</div>

yii2-app-basic/views/builds/facil.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\SqlDataProvider;

/** @var yii\web\View $this */
/** @var yii\data\SqlDataProvider $faciles */

$this->title = 'Buscar';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contenedor-titulo">
    <h1 class="titulo">BUILDS FÁCILES DE JUGAR</h1>
</div>

<div class="contenedor-tabla-tresrecientes">
    <?= GridView::widget([
        'dataProvider' => $faciles,
        'columns' => [
            [
                'attribute' => 'nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model['nombre']), ['builds/ver', 'nombre' => $model['nombre']]);
                },
            ],
            'efectividad',
            'complejidad',
            'personaje_nombre',
            'casco_nombre',
            'collar_nombre',
            'arma_nombre',
            'armadura_nombre',
            'botas_nombre',
            'anillo_nombre',
        ],
        'tableOptions' => ['class' => 'tabla-tresRecientes'],
        'summary' => '', // Oculta el resumen
    ]); ?>
</div>

<!-- Botón de vuelta -->
<div class="contenedor-titulo">
    <?= Html::a('VOLVER A EXPLORAR', ['builds/explorar'], ['class' => 'boton-vuelta-a-explorar']) ?>
</div>

yii2-app-basic/views/builds/jefes.php
<?php

use app\models\Builds;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\web\Controller;
use yii\data\SqlDataProvider;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Builds';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="contenedor-titulo">
    <h1 class="titulo">BUILDS PARA ENFRENTAR JEFES</h1>
</div>

<div class="contenedor-tabla-tresrecientes">
    <?= GridView::widget([
        'dataProvider' => $filtroMapas,
        'columns' => [
            [
                'attribute' => 'nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model['nombre']), ['builds/ver', 'nombre' => $model['nombre']]);
                },
            ],
            [
                'attribute' => 'efectividad',
                'value' => function ($model) {
                    return empty($model['efectividad']) ? 'N/A' : $model['efectividad'];
                },
            ],
            [
                'attribute' => 'complejidad',
                'value' => function ($model) {
                    return empty($model['complejidad']) ? 'N/A' : $model['complejidad'];
                },
            ],
            [
                'attribute' => 'personaje_nombre',
                'value' => function ($model) {
                    return empty($model['personaje_nombre']) ? 'N/A' : $model['personaje_nombre'];
                },
            ],
            [
                'attribute' => 'casco_nombre',
                'value' => function ($model) {
                    return empty($model['casco_nombre']) ? 'N/A' : $model['casco_nombre'];
                },
            ],
            [
                'attribute' => 'collar_nombre',
                'value' => function ($model) {
                    return empty($model['collar_nombre']) ? 'N/A' : $model['collar_nombre'];
                },
            ],
            [
                'attribute' => 'arma_nombre',
                'value' => function ($model) {
                    return empty($model['arma_nombre']) ? 'N/A' : $model['arma_nombre'];
                },
            ],
            [
                'attribute' => 'armadura_nombre',
                'value' => function ($model) {
                    return empty($model['armadura_nombre']) ? 'N/A' : $model['armadura_nombre'];
                },
            ],
            [
                'attribute' => 'botas_nombre',
                'value' => function ($model) {
                    return empty($model['botas_nombre']) ? 'N/A' : $model['botas_nombre'];
                },
            ],
            [
                'attribute' => 'anillo_nombre',
                'value' => function ($model) {
                    return empty($model['anillo_nombre']) ? 'N/A' : $model['anillo_nombre'];
                },
            ],
        ],
        'tableOptions' => ['class' => 'tabla-tresRecientes'],
        'summary' => '', // Oculta el resumen
    ]); ?>
</div>

<div class="contenedor-titulo">
    <?= Html::a('VOLVER A EXPLORAR', ['builds/explorar'], ['class' => 'boton-vuelta-a-explorar']) ?>
</div>

yii2-app-basic/views/builds/resultados.php
<?php

use app\models\Builds;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\web\Controller;
use yii\data\SqlDataProvider;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Builds';
$this->params['breadcrumbs'][] = $this->title;
?>